require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

module Phcscriptcdn
  RSpec.describe Scriptcdn::ScripturlsController, type: :controller do

    # This should return the minimal set of attributes required to create a valid
    # Scriptcdn::Scripturl. As you add validations to Scriptcdn::Scripturl, be sure to
    # adjust the attributes here as well.
    let(:valid_attributes) {
      skip("Add a hash of attributes valid for your model")
    }

    let(:invalid_attributes) {
      skip("Add a hash of attributes invalid for your model")
    }

    # This should return the minimal set of values that should be in the session
    # in order to pass any filters (e.g. authentication) defined in
    # Scriptcdn::ScripturlsController. Be sure to keep this updated too.
    let(:valid_session) { {} }

    describe "GET #index" do
      it "assigns all scriptcdn_scripturls as @scriptcdn_scripturls" do
        scripturl = Scriptcdn::Scripturl.create! valid_attributes
        get :index, {}, valid_session
        expect(assigns(:scriptcdn_scripturls)).to eq([scripturl])
      end
    end

    describe "GET #show" do
      it "assigns the requested scriptcdn_scripturl as @scriptcdn_scripturl" do
        scripturl = Scriptcdn::Scripturl.create! valid_attributes
        get :show, {:id => scripturl.to_param}, valid_session
        expect(assigns(:scriptcdn_scripturl)).to eq(scripturl)
      end
    end

    describe "GET #new" do
      it "assigns a new scriptcdn_scripturl as @scriptcdn_scripturl" do
        get :new, {}, valid_session
        expect(assigns(:scriptcdn_scripturl)).to be_a_new(Scriptcdn::Scripturl)
      end
    end

    describe "GET #edit" do
      it "assigns the requested scriptcdn_scripturl as @scriptcdn_scripturl" do
        scripturl = Scriptcdn::Scripturl.create! valid_attributes
        get :edit, {:id => scripturl.to_param}, valid_session
        expect(assigns(:scriptcdn_scripturl)).to eq(scripturl)
      end
    end

    describe "POST #create" do
      context "with valid params" do
        it "creates a new Scriptcdn::Scripturl" do
          expect {
            post :create, {:scriptcdn_scripturl => valid_attributes}, valid_session
          }.to change(Scriptcdn::Scripturl, :count).by(1)
        end

        it "assigns a newly created scriptcdn_scripturl as @scriptcdn_scripturl" do
          post :create, {:scriptcdn_scripturl => valid_attributes}, valid_session
          expect(assigns(:scriptcdn_scripturl)).to be_a(Scriptcdn::Scripturl)
          expect(assigns(:scriptcdn_scripturl)).to be_persisted
        end

        it "redirects to the created scriptcdn_scripturl" do
          post :create, {:scriptcdn_scripturl => valid_attributes}, valid_session
          expect(response).to redirect_to(Scriptcdn::Scripturl.last)
        end
      end

      context "with invalid params" do
        it "assigns a newly created but unsaved scriptcdn_scripturl as @scriptcdn_scripturl" do
          post :create, {:scriptcdn_scripturl => invalid_attributes}, valid_session
          expect(assigns(:scriptcdn_scripturl)).to be_a_new(Scriptcdn::Scripturl)
        end

        it "re-renders the 'new' template" do
          post :create, {:scriptcdn_scripturl => invalid_attributes}, valid_session
          expect(response).to render_template("new")
        end
      end
    end

    describe "PUT #update" do
      context "with valid params" do
        let(:new_attributes) {
          skip("Add a hash of attributes valid for your model")
        }

        it "updates the requested scriptcdn_scripturl" do
          scripturl = Scriptcdn::Scripturl.create! valid_attributes
          put :update, {:id => scripturl.to_param, :scriptcdn_scripturl => new_attributes}, valid_session
          scripturl.reload
          skip("Add assertions for updated state")
        end

        it "assigns the requested scriptcdn_scripturl as @scriptcdn_scripturl" do
          scripturl = Scriptcdn::Scripturl.create! valid_attributes
          put :update, {:id => scripturl.to_param, :scriptcdn_scripturl => valid_attributes}, valid_session
          expect(assigns(:scriptcdn_scripturl)).to eq(scripturl)
        end

        it "redirects to the scriptcdn_scripturl" do
          scripturl = Scriptcdn::Scripturl.create! valid_attributes
          put :update, {:id => scripturl.to_param, :scriptcdn_scripturl => valid_attributes}, valid_session
          expect(response).to redirect_to(scripturl)
        end
      end

      context "with invalid params" do
        it "assigns the scriptcdn_scripturl as @scriptcdn_scripturl" do
          scripturl = Scriptcdn::Scripturl.create! valid_attributes
          put :update, {:id => scripturl.to_param, :scriptcdn_scripturl => invalid_attributes}, valid_session
          expect(assigns(:scriptcdn_scripturl)).to eq(scripturl)
        end

        it "re-renders the 'edit' template" do
          scripturl = Scriptcdn::Scripturl.create! valid_attributes
          put :update, {:id => scripturl.to_param, :scriptcdn_scripturl => invalid_attributes}, valid_session
          expect(response).to render_template("edit")
        end
      end
    end

    describe "DELETE #destroy" do
      it "destroys the requested scriptcdn_scripturl" do
        scripturl = Scriptcdn::Scripturl.create! valid_attributes
        expect {
          delete :destroy, {:id => scripturl.to_param}, valid_session
        }.to change(Scriptcdn::Scripturl, :count).by(-1)
      end

      it "redirects to the scriptcdn_scripturls list" do
        scripturl = Scriptcdn::Scripturl.create! valid_attributes
        delete :destroy, {:id => scripturl.to_param}, valid_session
        expect(response).to redirect_to(scriptcdn_scripturls_url)
      end
    end

  end
end
